apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  capacity:
    storage: 5Gi
  hostPath:
    path: /home/ec2-user/mysql1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  capacity:
    storage: 5Gi
  hostPath:
    path: /home/ec2-user/mysql2
