apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: deploy2
  labels:
     app: mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
      - name: dockerhub-key
      containers:
      - name: db-ctr
        image: 28141108/java-mvn-privaterepos:mysql
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
           secretKeyRef:
                name: mysql-password
                key: MYSQL_ROOT_PASSWORD
        volumeMounts:
        - name: mysql-store
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
   - metadata:
      name: mysql-store
     spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: "manual"
      resources:
        requests:
        storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
  clusterIP: None
  selector:
     app: mysql
